theme: jekyll-theme-cayman
title: ADoBo
description: A shared task on Automatic Detection of Borrowings at IberLEF 2021
show_downloads: true

github:
  session: https://youtu.be/k6w9Kbv5-Is
  codalab: https://competitions.codalab.org/competitions/28771
  google_group: https://groups.google.com/g/adobo-task
  guidelines: https://adobo-task.github.io/docs/guidelines.pdf
