theme: jekyll-theme-cayman
title: [ADoBo]
description: [A shared task on Automatic Detection of Borrowings at IberLEF 2021]
github:
  codalab: https://competitions.codalab.org/competitions/28771
  google_group: https://groups.google.com/g/adobo-task
